Module1 task1
htmlacademy-vue/138767-pizza-1 pull request #1
Opened 2021-07-28 19:48 UTC by Lavrik15

2021-07-28 20:17 UTC, gustoase requested changes
В целом получилось хорошо, надо чуть доработать нейминг)

2021-07-28 20:17 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +    setDiameterSize(data) {
Название не подходит по смыслу, мы ничего не устанавливаем по факту, хорошо бы придумать более рабочее имя)

2021-07-29 07:44 UTC, Lavrik15 commented on src/frontend/src/views/Index.vue
> +    setDiameterSize(data) {
Поправил

2021-07-29 09:11 UTC, gustoase approved these changes

2021-07-29 09:12 UTC, merged