Module2 task1
htmlacademy-vue/138767-pizza-1 pull request #2
Opened 2021-08-01 20:13 UTC by Lavrik15

2021-08-01 20:54 UTC, Djaler requested changes

2021-08-01 20:54 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
draggable должен отключаться, когда достигнуто максимальное количество ингредиентов

2021-08-01 20:54 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      return this.dough.price + this.sauce.price + ingredientsPrice;
нужно ещё умножать это дело на модификатор размера

2021-08-01 20:54 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      if (!this.ingredients.length) {
Как вариант, чтобы удобнее было управлять данными о выбранных ингредиента:
можно хранить их в виде объекта, где ключ - тип ингредиента, а значение - количество. Тогда проще будет менять значение, искать и т.д.

2021-08-02 17:33 UTC, Lavrik15 commented on src/frontend/src/views/Index.vue
> +      return this.dough.price + this.sauce.price + ingredientsPrice;
ничёсе) дорого выходит тогда)

2021-08-02 17:34 UTC, Lavrik15 commented on src/frontend/src/views/Index.vue
> +      if (!this.ingredients.length) {
Классный вариант, буду знать о нем, но я сейчас не хотел бы переписывать :)

2021-08-02 17:37 UTC, merged